server:
  port: 8088

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  data:
    redis:
      use-redis-cache: true
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-version: 0
    baseline-on-migrate: true
api:
  prefix: /api/v1
jwt:
  expiration: 7200 # 2 tiếng 2 * 60 * 60
  expiration-refreshToken: 655_200 # 7 ngày 7 * 24 * 60 * 60
  secretKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

#healthCheck
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: health,info

#Swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

logging:
  level:
    org:
      springframework.security: DEBUG