server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DATASOURCE_URL}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  data:
    redis:
      use-redis-cache: true
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-version: 0
    baseline-on-migrate: true

api:
  prefix: /api/v1
jwt:
  expiration: 7200 # 2 tiếng 2 * 60 * 60
  expiration-refreshToken: 655_200 # 7 ngày 7 * 24 * 60 * 60
  secretKey: ${SECRET_KEY}

#healthCheck
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: health,info

#Swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

logging:
  level:
    org:
      springframework.security: DEBUG

payment:
  vnPay:
    vnp_PayUrl: ${VNPAY_URL}
    vnp_ReturnUrl: ${VNPAY_RETURN_URL}
    vnp_IpnUrl: ${VNPAY_IPN_URL}
    tmnCode: ${VNPAY_TMN_CODE}
    secretKey: ${VNPAY_SECRET_KEY}
    version: "2.1.0"
    command: "pay"
    orderType: "other"
    bankCode: "NCB"
    vnp_CurrCode: "VND"


